### ISSUE TITLE
Class Test.main() Exception

### ISSUE THREAD

**Issue by xlvecle** [1tianrui/newSqlHelperForJava#1]
`java.lang.StringIndexOutOfBoundsException: String index out of range: 19
    at java.lang.String.charAt(String.java:658)
    at sql.SqlSovleHelper.resolveTableName(SqlSovleHelper.java:20)
    at sql.SqlSolver.solveTableEntity(SqlSolver.java:12)
    at Sql2Spring.<init>(Sql2Spring.java:20)
    at Test.main(Test.java:19)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

**Comment by 1tianrui** [comment]
fix done
